// Detailní průvodce po týdnech – vychází z dokumentu Tréninkový plán Podzim 2026 v5.2
export interface WeekGuide {
  wk: number; title: string; block: string; dates: string; mode: string;
  focus: string; why: string; points: string[];
  rotation: { slot: string; value: string }[];
  main: { lift: string; text: string }[];
  cardio: string; rpe: string;
}
export const WEEK_GUIDE: WeekGuide[] = [
  {
    wk: 1, title: 'Blok A — Akumulace', block: 'Blok A', dates: '18.–24. 8.', mode: 'objemový',
    focus: 'Reacklimatizace, znovunastavení vah po restartu. Objem 8/6 op., jedna těžká overload expozice.',
    why: 'Rozjezd bloku. Po restartu se vrací pracovní kapacita – jedeš 8 a 6 opakování, ale hned s jednou těžkou expozicí (overload trojka), aby tělo nezapomnělo na vysoké procento. Israetel: adaptace na 87–95 % 1RM potřebuje opakovanou expozici, ne jen pár těžkých týdnů na konci.',
    points: ['Doplňky jedou na vyšší opakování (8–12) – víc objemu, nižší váhy.', 'Face pull navíc na zdraví ramen.', 'Nohy drž silově, nepřidávej vysokoopakovkové drtičky.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Bulharský dřep' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pauzový / Spoto press' }, { slot: 'Triceps (místo dipů)', value: 'Triceps pushdown' }, { slot: 'Veslování', value: 'Barbell row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'jednoručky · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '145×8 (Objemová) → 162.5×3 (OVERLOAD) → 152.5×6 (Back-off) → 152.5×6 (Back-off)' }, { lift: 'Bench (Út)', text: '100×8 (Objemová) → 112.5×3 (OVERLOAD) → 105×6 (Back-off) → 105×6 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '180×8 (Objemová) → 202.5×3 (OVERLOAD) → 190×6 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Pracovní série RPE 7–8 (2–3 opakování v zásobě). Overload RPE 8.',
  },
  {
    wk: 2, title: 'Blok A — Akumulace', block: 'Blok A', dates: '25.–31. 8.', mode: 'objemový',
    focus: 'Double progression – přidat opakování/váhu. Overload dvojka.',
    why: 'Double progression – přidáváš buď opakování, nebo váhu, ne obojí. Overload jde z trojky na dvojku, takže expozice je těžší, ale kratší. Objem zůstává stejný.',
    points: ['Doplňky jedou na vyšší opakování (8–12) – víc objemu, nižší váhy.', 'Face pull navíc na zdraví ramen.', 'Nohy drž silově, nepřidávej vysokoopakovkové drtičky.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Bulharský dřep' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pauzový / Spoto press' }, { slot: 'Triceps (místo dipů)', value: 'Triceps pushdown' }, { slot: 'Veslování', value: 'Barbell row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'jednoručky · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '147.5×8 (Objemová) → 167.5×2 (OVERLOAD) → 152.5×6 (Back-off) → 152.5×5 (Back-off)' }, { lift: 'Bench (Út)', text: '102.5×8 (Objemová) → 115×2 (OVERLOAD) → 107.5×6 (Back-off) → 107.5×5 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '185×8 (Objemová) → 207.5×2 (OVERLOAD) → 195×6 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Pracovní série RPE 7–8 (2–3 opakování v zásobě). Overload RPE 8.',
  },
  {
    wk: 3, title: 'Blok A — Akumulace', block: 'Blok A', dates: '1.–7. 9.', mode: 'silový',
    focus: 'Vrchol akumulace (tvůj oblíbený „týden 3“ styl). Nejvyšší objem bloku.',
    why: 'Vrchol bloku A – nejvyšší kombinace objemu a intenzity. Tohle je ten typ týdne, který ti dřív seděl nejvíc. Overload dvojka je ~92 % TM. Pokud RPE přeleze 9, uber back-off sérii, ne váhu na overloadu.',
    points: ['Doplňky silově (4–6 op.), přidej zátěž na pull-upy a dipy nahrazující triceps.', 'Nordic curl / GHD jen v tomhle typu týdne.', 'Veslování 4×5 místo 3×8–10.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Bulharský dřep' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pauzový / Spoto press' }, { slot: 'Triceps (místo dipů)', value: 'Triceps pushdown' }, { slot: 'Veslování', value: 'Barbell row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'jednoručky · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '152.5×6 (Objemová) → 170×2 (OVERLOAD) → 155×6 (Back-off) → 155×5 (Back-off)' }, { lift: 'Bench (Út)', text: '105×6 (Objemová) → 117.5×2 (OVERLOAD) → 110×6 (Back-off) → 110×5 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '187.5×6 (Objemová) → 212.5×2 (OVERLOAD) → 197.5×6 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Top set RPE 8–9 (1–2 v zásobě). Back-offy RPE 8.',
  },
  {
    wk: 4, title: 'Deload', block: 'Blok A', dates: '8.–14. 9.', mode: 'deload',
    focus: 'Deload −40 % objemu. Aktivní regenerace, technika. HRV/readiness zpět nahoru.',
    why: 'Deload. Objem dolů o ~40 %, váhy ~72 % – aktivní regenerace, ne volno. Cílem je nechat odejít únavu z bloku A, aby blok B mohl začít z čistého štítu. HRV a readiness se mají vrátit nahoru.',
    points: ['Nejezdi do selhání, RPE max 6–7.', 'Doplňky zredukované na 2 série.', 'Spánek a jídlo priorita – deload je práce na regeneraci.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Bulharský dřep' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pauzový / Spoto press' }, { slot: 'Triceps (místo dipů)', value: 'Triceps pushdown' }, { slot: 'Veslování', value: 'Barbell row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'jednoručky · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '130×5 (Deload) → 130×5 (Deload) → 132.5×5 (Deload)' }, { lift: 'Bench (Út)', text: '90×5 (Deload) → 90×5 (Deload) → 92.5×5 (Deload)' }, { lift: 'Mrtvý tah (Pá)', text: '160×5 (Deload) → 160×5 (Deload) → 165×5 (Deload)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Vše RPE 6–7. Má to být lehké.',
  },
  {
    wk: 5, title: 'Blok B — Síla', block: 'Blok B', dates: '15.–21. 9.', mode: 'silový',
    focus: 'Vstup do síly. Zavádíme pětky/trojky. Ramp → top → overload → back-off.',
    why: 'Start bloku B. Přecházíš z 8/6 opakování na 5/3 – míň opakování, vyšší kvalita. Struktura je pořád stejná vlna, jen posunutá k intenzitě. Sekundární dřep se mění na pin dřep (mrtvý bod).',
    points: ['Doplňky silově (4–6 op.), přidej zátěž na pull-upy a dipy nahrazující triceps.', 'Nordic curl / GHD jen v tomhle typu týdne.', 'Veslování 4×5 místo 3×8–10.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Chodící výpady' }, { slot: 'Dřep – variace', value: 'Pin dřep (z kolíků)' }, { slot: 'Bench – variace', value: 'Dlouhý pauzový (3 s) / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Overhead extension' }, { slot: 'Veslování', value: 'Chest-supported row' }, { slot: 'Pull-up úchop', value: 'neutrál · střední' }, { slot: 'Biceps', value: 'šikmá lavice · jednoručky' }, { slot: 'Hamstringy', value: 'GHD raise' }],
    main: [{ lift: 'Dřep (Po)', text: '157.5×5 (TOP) → 165×3 (OVERLOAD) → 152.5×5 (Back-off) → 152.5×5 (Back-off)' }, { lift: 'Bench (Út)', text: '107.5×5 (TOP) → 112.5×3 (OVERLOAD) → 105×5 (Back-off) → 105×5 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '195×5 (TOP) → 205×3 (OVERLOAD) → 187.5×5 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Top set RPE 8–9 (1–2 v zásobě). Back-offy RPE 8.',
  },
  {
    wk: 6, title: 'Blok B — Síla', block: 'Blok B', dates: '22.–28. 9.', mode: 'objemový',
    focus: 'Progrese, čtyřky na top setu. Objem doplňků nahoru (objemový týden).',
    why: 'Objemový týden uvnitř silového bloku – doplňky jdou na vyšší opakování, hlavní cviky drží čtyřky. Rotace cviků (výpady, overhead extension) dává nový podnět bez nárůstu únavy.',
    points: ['Doplňky jedou na vyšší opakování (8–12) – víc objemu, nižší váhy.', 'Face pull navíc na zdraví ramen.', 'Nohy drž silově, nepřidávej vysokoopakovkové drtičky.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Chodící výpady' }, { slot: 'Dřep – variace', value: 'Pin dřep (z kolíků)' }, { slot: 'Bench – variace', value: 'Dlouhý pauzový (3 s) / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Overhead extension' }, { slot: 'Veslování', value: 'Chest-supported row' }, { slot: 'Pull-up úchop', value: 'neutrál · střední' }, { slot: 'Biceps', value: 'šikmá lavice · jednoručky' }, { slot: 'Hamstringy', value: 'GHD raise' }],
    main: [{ lift: 'Dřep (Po)', text: '160×4 (TOP) → 167.5×2 (OVERLOAD) → 155×5 (Back-off) → 155×4 (Back-off)' }, { lift: 'Bench (Út)', text: '110×4 (TOP) → 115×2 (OVERLOAD) → 107.5×5 (Back-off) → 107.5×4 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '200×4 (TOP) → 210×2 (OVERLOAD) → 192.5×5 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Pracovní série RPE 7–8 (2–3 opakování v zásobě). Overload RPE 8.',
  },
  {
    wk: 7, title: 'Blok B — Síla', block: 'Blok B', dates: '29. 9.–5. 10.', mode: 'silový',
    focus: 'Nejvyšší intenzita bloku B – trojky/dvojky. Silové doplňky.',
    why: 'Nejtěžší týden bloku B. Trojky a dvojky na hlavních cvicích, doplňky silově. Tady se ukáže, jestli deload W4 zabral. Když RPE top setu přeleze 9,5, vynech back-offy.',
    points: ['Doplňky silově (4–6 op.), přidej zátěž na pull-upy a dipy nahrazující triceps.', 'Nordic curl / GHD jen v tomhle typu týdne.', 'Veslování 4×5 místo 3×8–10.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Chodící výpady' }, { slot: 'Dřep – variace', value: 'Pin dřep (z kolíků)' }, { slot: 'Bench – variace', value: 'Dlouhý pauzový (3 s) / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Overhead extension' }, { slot: 'Veslování', value: 'Chest-supported row' }, { slot: 'Pull-up úchop', value: 'neutrál · střední' }, { slot: 'Biceps', value: 'šikmá lavice · jednoručky' }, { slot: 'Hamstringy', value: 'GHD raise' }],
    main: [{ lift: 'Dřep (Po)', text: '167.5×3 (TOP) → 172.5×2 (OVERLOAD) → 157.5×4 (Back-off) → 157.5×4 (Back-off)' }, { lift: 'Bench (Út)', text: '115×3 (TOP) → 117.5×2 (OVERLOAD) → 107.5×4 (Back-off) → 107.5×4 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '207.5×3 (TOP) → 215×2 (OVERLOAD) → 195×4 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Top set RPE 8–9 (1–2 v zásobě). Back-offy RPE 8.',
  },
  {
    wk: 8, title: 'Deload', block: 'Blok B', dates: '6.–12. 10.', mode: 'deload',
    focus: 'Deload −50 %. Před intenzifikací plně zregenerovat.',
    why: 'Druhý deload. Před blokem C musíš být čerstvý – intenzifikace je nejnáročnější část plánu. Objem dolů o ~50 %, váhy ~77 %.',
    points: ['Nejezdi do selhání, RPE max 6–7.', 'Doplňky zredukované na 2 série.', 'Spánek a jídlo priorita – deload je práce na regeneraci.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Chodící výpady' }, { slot: 'Dřep – variace', value: 'Pin dřep (z kolíků)' }, { slot: 'Bench – variace', value: 'Dlouhý pauzový (3 s) / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Overhead extension' }, { slot: 'Veslování', value: 'Chest-supported row' }, { slot: 'Pull-up úchop', value: 'neutrál · střední' }, { slot: 'Biceps', value: 'šikmá lavice · jednoručky' }, { slot: 'Hamstringy', value: 'GHD raise' }],
    main: [{ lift: 'Dřep (Po)', text: '140×3 (Deload) → 140×3 (Deload) → 142.5×3 (Deload)' }, { lift: 'Bench (Út)', text: '95×3 (Deload) → 95×3 (Deload) → 97.5×3 (Deload)' }, { lift: 'Mrtvý tah (Pá)', text: '172.5×3 (Deload) → 172.5×3 (Deload) → 177.5×3 (Deload)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Vše RPE 6–7. Má to být lehké.',
  },
  {
    wk: 9, title: 'Blok C — Intenzifikace', block: 'Blok C', dates: '13.–19. 10.', mode: 'silový',
    focus: 'Vstup do intenzifikace – tvůj „pozdní“ vlnový systém: dvojka na top, pak objemové back-offy. 120 na benchi má být LEHKÝCH.',
    why: 'Start intenzifikace. Přecházíš na dvojky na top setu a objemové back-offy. Tady začíná ta část, kterou jsi popisoval: 120 na benchi má být LEHKÝCH. Pokud není, je to signál zpomalit, ne přidat.',
    points: ['Doplňky silově (4–6 op.), přidej zátěž na pull-upy a dipy nahrazující triceps.', 'Nordic curl / GHD jen v tomhle typu týdne.', 'Veslování 4×5 místo 3×8–10.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Leg press' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pin press / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Skull crusher / JM press' }, { slot: 'Veslování', value: 'Pendlay row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'EZ osa · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '162.5×3 (Nájezd) → 172.5×2 (TOP) → 157.5×5 (Back-off) → 157.5×5 (Back-off)' }, { lift: 'Bench (Út)', text: '112.5×3 (Nájezd) → 117.5×2 (TOP) → 107.5×5 (Back-off) → 107.5×5 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '202.5×3 (Nájezd) → 215×2 (TOP) → 195×5 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Top set RPE 8–9 (1–2 v zásobě). Back-offy RPE 8.',
  },
  {
    wk: 10, title: 'Blok C — Intenzifikace', block: 'Blok C', dates: '20.–26. 10.', mode: 'objemový',
    focus: 'První top singly (95 %). 120 kg bench lehce, 125 se objevuje.',
    why: 'První top singly (95 %). Bench 120×1 by měl jít hladce – to je kontrolní bod před 130. Doplňky jdou objemově, aby se udržela svalová hmota při klesajícím objemu hlavních cviků.',
    points: ['Doplňky jedou na vyšší opakování (8–12) – víc objemu, nižší váhy.', 'Face pull navíc na zdraví ramen.', 'Nohy drž silově, nepřidávej vysokoopakovkové drtičky.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Leg press' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pin press / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Skull crusher / JM press' }, { slot: 'Veslování', value: 'Pendlay row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'EZ osa · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '167.5×2 (Nájezd) → 175×1 (TOP single) → 160×4 (Back-off) → 160×3 (Back-off)' }, { lift: 'Bench (Út)', text: '115×2 (Nájezd) → 120×1 (TOP single) → 110×4 (Back-off) → 110×3 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '207.5×2 (Nájezd) → 217.5×1 (TOP single) → 200×4 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Pracovní série RPE 7–8 (2–3 opakování v zásobě). Overload RPE 8.',
  },
  {
    wk: 11, title: 'Blok C — Intenzifikace', block: 'Blok C', dates: '27. 10.–2. 11.', mode: 'silový',
    focus: 'Nejtěžší tréninkový týden – singly 97 %. 125 kg jako těžší top single.',
    why: 'Nejtěžší tréninkový týden celého plánu – singly na 97 %. Bench 122,5, dřep 180, tah 222,5. RPE 9 znamená: šla by ještě jedna, ale sotva. Nejezdi na RPE 10, na to je testovací týden.',
    points: ['Doplňky silově (4–6 op.), přidej zátěž na pull-upy a dipy nahrazující triceps.', 'Nordic curl / GHD jen v tomhle typu týdne.', 'Veslování 4×5 místo 3×8–10.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Leg press' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pin press / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Skull crusher / JM press' }, { slot: 'Veslování', value: 'Pendlay row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'EZ osa · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '170×2 (Nájezd) → 180×1 (TOP single) → 162.5×3 (Back-off) → 162.5×3 (Back-off)' }, { lift: 'Bench (Út)', text: '117.5×2 (Nájezd) → 122.5×1 (TOP single) → 112.5×3 (Back-off) → 112.5×3 (Back-off)' }, { lift: 'Mrtvý tah (Pá)', text: '212.5×2 (Nájezd) → 222.5×1 (TOP single) → 202.5×3 (Back-off)' }],
    cardio: 'HIIT středa + sobota beze změny. Volitelný lehký Z2 běh v neděli, do 5 km – není povinný.', rpe: 'Top set RPE 8–9 (1–2 v zásobě). Back-offy RPE 8.',
  },
  {
    wk: 12, title: 'Taper', block: 'Taper', dates: '3.–9. 11.', mode: 'taper',
    focus: 'Taper −60 % objemu, intenzita zachována. Nácvik openerů. Únava odchází.',
    why: 'Taper. Objem dolů o ~60 %, intenzita zůstává. Jedeš openery a druhé pokusy, žádné back-offy. Dvou-faktorový model: únava odchází rychleji než fitness, takže výkon vyskočí nad dosavadní úroveň. Běh tento týden vynech.',
    points: ['Žádné back-off série.', 'Nacvič si opener – váhu, kterou dáš i ve špatný den.', 'Vynech běh, HIIT ber jako lehké.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Leg press' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pin press / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Skull crusher / JM press' }, { slot: 'Veslování', value: 'Pendlay row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'EZ osa · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '167.5×1 (Opener) → 157.5×2 (Druhá) → 147.5×3 (Objem)' }, { lift: 'Bench (Út)', text: '115×1 (Opener) → 107.5×2 (Druhá) → 102.5×3 (Objem)' }, { lift: 'Mrtvý tah (Pá)', text: '207.5×1 (Opener) → 195×2 (Druhá) → 185×3 (Objem)' }],
    cardio: 'Běh tento týden vynech (minimalizace interference před maximem – Viada). HIIT St + So ber lehce.', rpe: 'Vše RPE 7. Žádné hrdinství.',
  },
  {
    wk: 13, title: 'TEST MAXIM', block: 'TEST MAXIM', dates: '10.–16. 11.', mode: 'test',
    focus: 'Test maxim. Dvou-faktorový model: únava pryč, fitness zůstala → výkon vyskočí. Cíle: bench 130, dřep 190, mrtvý tah 230+.',
    why: 'Testovací týden. Každý den jeden lift, postupné singly až na cíl. Před testem: dobrý spánek, +100 g sacharidů ráno, žádný běh. Mezi pokusy 3–5 min. Zastav, když technika povolí.',
    points: ['Jeden lift denně, plný odpočinek mezi pokusy.', 'Rozjezd → cíl → volitelný PR pokus.', 'Když druhý pokus jde hladce, jdi na PR. Když ne, spokoj se s cílem.'],
    rotation: [{ slot: 'Nohy – doplněk', value: 'Leg press' }, { slot: 'Dřep – variace', value: 'Pauzový dřep (2 s)' }, { slot: 'Bench – variace', value: 'Pin press / Spoto' }, { slot: 'Triceps (místo dipů)', value: 'Skull crusher / JM press' }, { slot: 'Veslování', value: 'Pendlay row' }, { slot: 'Pull-up úchop', value: 'úzko/podhmat · široko' }, { slot: 'Biceps', value: 'EZ osa · kladívkový' }, { slot: 'Hamstringy', value: 'Nordic curl' }],
    main: [{ lift: 'Dřep (Po)', text: '150×1 (Rozjezd) → 170×1 (Rozjezd) → 190×1 (CÍL) → 195×1 (PR (volitelně))' }, { lift: 'Bench (Út)', text: '100×1 (Rozjezd) → 115×1 (Rozjezd) → 125×1 (Rozjezd) → 130×1 (CÍL) → 132.5×1 (PR (volitelně))' }, { lift: 'Mrtvý tah (Pá)', text: '180×1 (Rozjezd) → 207.5×1 (Rozjezd) → 230×1 (CÍL) → 235×1 (PR pokus)' }],
    cardio: 'Běh tento týden vynech (minimalizace interference před maximem – Viada). HIIT St + So ber lehce.', rpe: 'Rozjezdy RPE 7–8, cílový pokus RPE 9–10.',
  },
];
